@baseurl = https://8080-Gurincha-springwikiap-d7karjvwtxc.ws-us114.gitpod.io

###
GET {{baseurl}}/preco

###
POST {{baseurl}}/preco
Content-Type: application/json

{
    "preco": "R$150,00",
    "local_de_compra": "Amazon"
}

###
PUT {{baseurl}}/preco/2
Content-Type: application/json

{
    "preco": "R$70,00",
    "local_de_compra": "Amazon"
}

PUT {{baseurl}}/preco/2
Content-Type: application/json

{
    "preco": "R$200,00",
    "local_de_compra": "Saraiva"

}
###
DELETE {{baseurl}}/preco/2